(async()=>{try{
await refresh(true);await $('statusHelp').onclick();const statusLegend=$('infoDialog').open&&$('infoContent').querySelectorAll('.dot').length===4&&!document.querySelector('.right').textContent.includes('Зелёная метка');$('infoDialog').close();await updateCloseChoice();const clearClosePreference=$('resetCloseChoice').textContent==='Снова спрашивать при закрытии'&&$('closeChoiceStatus').textContent.startsWith('Сейчас:');const analysis=await request('project-analysis?project='+studioState.project);
await $('inspectProject').onclick();const detectionVisible=$('detectionDialog').open&&$('detectionBody').textContent.includes('Как внедрять перевод');$('detectionDialog').close();
const rows=await request('records?file='+studioState.snapshot.files[0].id);await showRecordContext(rows.rows[0].id);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
const body=$('infoContent'),phrase=body.querySelector('[data-context-id]'),bodyRect=body.getBoundingClientRect(),phraseRect=phrase.getBoundingClientRect();
const context={directions:body.textContent.includes('До выбранной фразы')&&body.textContent.includes('После выбранной фразы'),selectedVisible:phraseRect.top>=bodyRect.top&&phraseRect.bottom<=bodyRect.bottom,initialScroll:body.scrollTop,closeFocused:document.activeElement===$('infoClose')};
const fixed=$('infoClose').getBoundingClientRect().top;body.scrollTop=body.scrollHeight;context.closePinned=fixed===$('infoClose').getBoundingClientRect().top;$('infoDialog').close();
const homeValid=studioState.viewMode==='home'&&!$('projectHome').hidden&&$('textPane').hidden;
await $('futureTab').onclick();const upcomingCount=document.querySelectorAll('.record').length;
await $('historyTab').onclick();const historyCount=document.querySelectorAll('.record').length;const process={upcomingCount,historyCount,title:$('fileTitle').textContent,historyTab:studioState.processTab,flagsFolders:!!$('badFolder')&&!!$('reviewFolder')};
await $('badFolder').onclick();const folderControls=!$('folderReviewControls').hidden&&$('folderReviewControls').contains($('executionModel'))&&!!$('folderReviewRun')&&!!$('folderClearMarks');await $('historyTab').onclick();process.folderControls=folderControls;process.neighbors={before:+$('context_before').value,after:+$('context_after').value,tokens:+$('context').value};const languageProbe=await request('language-preview',{text:'Bonjour, je suis très heureux de vous rencontrer et de parler avec vous aujourd’hui.',source_language:'English'});process.deletionControls=!!$('deleteProject')&&!!$('completeProject')&&!!$('completedProjects');process.archiveControls=!!$('hideProject')&&!!$('hiddenProjects')&&!!$('projectArchiveMenu');process.foreignPolicy=$('auto_foreign').checked;process.languageProbe=languageProbe;await $('preservedFolder').onclick();process.literalFolder={count:document.querySelectorAll('.record').length,reason:$('rows').textContent.includes('Почему оставлен оригинал'),total:studioState.snapshot.counts.preserved};process.literalFolder.actions=[...document.querySelector('.record .record-actions').querySelectorAll('button')].map(b=>b.textContent);process.literalFolder.readOnly=document.querySelector('.record textarea').readOnly;await document.querySelector('.record .record-actions button').onclick();process.literalFolder.choices=[...$('infoContent').querySelectorAll('[data-preserved-mode]')].map(b=>b.dataset.preservedMode);$('infoDialog').close();process.pinnedNavigation=getComputedStyle($('projectNav')).position==='sticky';

await $('errorsButton').onclick();process.bulkRetryButton=!!$('retryAllErrors')&&!$('retryAllErrors').disabled;const errorRepeat=$('infoContent').querySelector('[data-error-repeat]');process.errorRecovery=!!errorRepeat&&!$('infoContent').textContent.includes('Открыть строку');process.errorBudget=$('infoContent').textContent.includes('Полный запрос:');if(errorRepeat){await errorRepeat.onclick();process.retryChoices=$('infoContent').querySelectorAll('[data-retry-choice]').length;await $('infoContent').querySelector('[data-retry-choice="custom"]').onclick();process.customRetry=!!$('retryExecutionModel')&&!!$('enqueueCustomRetry');await new Promise(r=>setTimeout(r,700));process.autoBudget=$('retryBudget').textContent.includes('Полный запрос:')};$('infoDialog').close();process.jobChain=!!$('jobChain')&&$('projectHome').contains($('jobChain'));
process.closeState=await window.pywebview.api.get_close_state();
process.textPreview={scrollbars:[...document.querySelectorAll('.record textarea')].every(t=>getComputedStyle(t).overflowY==='hidden'&&getComputedStyle(t).resize==='none'),buttons:!!document.querySelector('.record .record-expand')};
const importTop=$('importButton').getBoundingClientRect().top;await $('projectArchiveMenu').onclick();process.projectManager={open:$('projectManager').open,stableLeft:importTop===$('importButton').getBoundingClientRect().top,name:$('managedProjectName').textContent,spacing:getComputedStyle($('hideProject').parentElement).gap};$('projectManagerClose').click();
process.sidebar={task:['jobState','progress','live','mainAction','runLimits','taskMenu','logDetails'].every(id=>$('taskCard').contains($(id))),setup:$('setupCard').contains($('translationSettings')),gap:$('setupCard').getBoundingClientRect().top-$('taskCard').getBoundingClientRect().bottom};
window.__featureProbe={statusLegend,clearClosePreference,passed:statusLegend&&clearClosePreference&&process.textPreview.scrollbars&&process.textPreview.buttons&&process.projectManager.open&&process.projectManager.stableLeft&&process.sidebar.task&&process.sidebar.setup&&process.sidebar.gap>=20&&process.errorRecovery&&process.autoBudget&&process.bulkRetryButton&&process.jobChain&&homeValid&&detectionVisible&&!!analysis.report&&context.selectedVisible&&context.closePinned&&context.directions&&upcomingCount===50&&historyCount>=0&&folderControls&&process.literalFolder.reason&&process.neighbors.before===12&&process.neighbors.after===8,
project:$('fileTitle').textContent,summary:$('projectSummary').textContent,mcp:$('mcpStatus').textContent,
errorsInProject:$('projectHome').contains($('errorsButton')),workflow:typeof showRecordContext==='function',limits:!!$('runLimits'),modelChoice:!!$('executionModel'),
detection:{engine:analysis.report?.engine.name,confidence:analysis.report?.engine.confidence,files:analysis.report?.scanned_files,importable:analysis.report?.capabilities.importable_files,gameWrite:analysis.report?.capabilities.game_write},detectionVisible,context,process};
}catch(e){window.__featureProbe={passed:false,error:e.stack}}})();
